# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.setwave = QtWidgets.QLineEdit(self.centralwidget)
        self.setwave.setGeometry(QtCore.QRect(180, 140, 113, 32))
        self.setwave.setObjectName("setwave")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 150, 121, 22))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 200, 141, 22))
        self.label_2.setObjectName("label_2")
        self.presentwave = QtWidgets.QLineEdit(self.centralwidget)
        self.presentwave.setGeometry(QtCore.QRect(180, 190, 113, 32))
        self.presentwave.setObjectName("presentwave")
        self.units = QtWidgets.QComboBox(self.centralwidget)
        self.units.setGeometry(QtCore.QRect(390, 140, 83, 32))
        self.units.setObjectName("units")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 270, 141, 22))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 320, 121, 22))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 370, 141, 22))
        self.label_5.setObjectName("label_5")
        self.shutter = QtWidgets.QComboBox(self.centralwidget)
        self.shutter.setGeometry(QtCore.QRect(390, 190, 83, 32))
        self.shutter.setObjectName("shutter")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 200, 51, 22))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 420, 61, 21))
        self.label_7.setObjectName("label_7")
        self.startwave = QtWidgets.QLineEdit(self.centralwidget)
        self.startwave.setGeometry(QtCore.QRect(180, 260, 113, 32))
        self.startwave.setObjectName("startwave")
        self.endwave = QtWidgets.QLineEdit(self.centralwidget)
        self.endwave.setGeometry(QtCore.QRect(180, 310, 113, 32))
        self.endwave.setObjectName("endwave")
        self.intervalwave = QtWidgets.QLineEdit(self.centralwidget)
        self.intervalwave.setGeometry(QtCore.QRect(180, 360, 113, 32))
        self.intervalwave.setObjectName("intervalwave")
        self.delaywave = QtWidgets.QLineEdit(self.centralwidget)
        self.delaywave.setGeometry(QtCore.QRect(180, 410, 113, 32))
        self.delaywave.setObjectName("delaywave")
        self.goscan = QtWidgets.QPushButton(self.centralwidget)
        self.goscan.setGeometry(QtCore.QRect(340, 300, 99, 30))
        self.goscan.setObjectName("goscan")
        self.abortscan = QtWidgets.QPushButton(self.centralwidget)
        self.abortscan.setGeometry(QtCore.QRect(340, 370, 99, 30))
        self.abortscan.setObjectName("abortscan")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(340, 150, 41, 22))
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 230, 491, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 450, 491, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(490, 230, 20, 231))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 230, 20, 231))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 80, 491, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(490, 90, 20, 141))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(0, 90, 20, 141))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.port = QtWidgets.QComboBox(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(550, 350, 151, 32))
        self.port.setObjectName("port")
        self.conectar = QtWidgets.QPushButton(self.centralwidget)
        self.conectar.setGeometry(QtCore.QRect(710, 360, 61, 21))
        self.conectar.setObjectName("conectar")
        self.refresh = QtWidgets.QPushButton(self.centralwidget)
        self.refresh.setGeometry(QtCore.QRect(780, 360, 61, 21))
        self.refresh.setObjectName("refresh")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(80, 10, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(180, 50, 141, 22))
        self.label_10.setObjectName("label_10")
        self.command = QtWidgets.QLineEdit(self.centralwidget)
        self.command.setGeometry(QtCore.QRect(650, 140, 113, 32))
        self.command.setObjectName("command")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(560, 150, 81, 22))
        self.label_11.setObjectName("label_11")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(780, 150, 61, 21))
        self.send.setObjectName("send")
        self.response = QtWidgets.QLineEdit(self.centralwidget)
        self.response.setGeometry(QtCore.QRect(650, 190, 113, 32))
        self.response.setObjectName("response")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(560, 200, 81, 22))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(620, 100, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(530, 90, 20, 151))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(540, 80, 331, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(540, 230, 331, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(860, 90, 20, 151))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(630, 400, 51, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.state = QtWidgets.QLabel(self.centralwidget)
        self.state.setGeometry(QtCore.QRect(680, 400, 101, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.state.setFont(font)
        self.state.setObjectName("state")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(640, 310, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(520, 290, 20, 151))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(530, 280, 341, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(860, 290, 20, 151))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(530, 430, 341, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(150, 100, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Monocromador"))
        self.label.setText(_translate("MainWindow", "Set wavelength"))
        self.label_2.setText(_translate("MainWindow", "Present wavelength"))
        self.label_3.setText(_translate("MainWindow", "Start Wavelength"))
        self.label_4.setText(_translate("MainWindow", "End Wavelength"))
        self.label_5.setText(_translate("MainWindow", "Inteval Wavelength"))
        self.label_6.setText(_translate("MainWindow", "Shutter"))
        self.label_7.setText(_translate("MainWindow", "Delay"))
        self.goscan.setText(_translate("MainWindow", "Go Scan"))
        self.abortscan.setText(_translate("MainWindow", "Abort Scan"))
        self.label_8.setText(_translate("MainWindow", "Units"))
        self.conectar.setText(_translate("MainWindow", "Connect"))
        self.refresh.setText(_translate("MainWindow", "Refresh"))
        self.label_9.setText(_translate("MainWindow", "Monocromador "))
        self.label_10.setText(_translate("MainWindow", "Cornerstone 130"))
        self.label_11.setText(_translate("MainWindow", "Command:"))
        self.send.setText(_translate("MainWindow", "Send"))
        self.label_12.setText(_translate("MainWindow", "Response:"))
        self.label_13.setText(_translate("MainWindow", "Command Terminal"))
        self.label_14.setText(_translate("MainWindow", "State:"))
        self.state.setText(_translate("MainWindow", "Disconnected"))
        self.label_15.setText(_translate("MainWindow", "Comunication"))
        self.label_16.setText(_translate("MainWindow", "Wavelength Parameters"))

